<?php

namespace Database\Seeders;

use App\Models\Product\Brand;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class BrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        // Truncate the table
        Brand::truncate();

        $brands = [
            ['en_name' => 'Pran', 'bn_name' => 'প্রাণ'],
            ['en_name' => 'Teer', 'bn_name' => 'তীর'],
            ['en_name' => 'Fresh', 'bn_name' => 'ফ্রেশ'],
            ['en_name' => 'ACI', 'bn_name' => 'এসিআই'],
            ['en_name' => 'BD Foods', 'bn_name' => 'বিডি ফুডস'],
            ['en_name' => 'Akij Food & Beverage', 'bn_name' => 'আকিজ ফুড অ্যান্ড বেভারেজ'],
            ['en_name' => 'Sajeeb Group', 'bn_name' => 'সজীব গ্রুপ'],
            ['en_name' => 'Kazi & Kazi Tea', 'bn_name' => 'কাজী অ্যান্ড কাজী টি'],
            ['en_name' => 'IFAD', 'bn_name' => 'ইফাদ'],
            ['en_name' => 'Bashundhara', 'bn_name' => 'বসুন্ধরা'],
            ['en_name' => 'Q&Q', 'bn_name' => 'কিউএন্ডকিউ'],
            ['en_name' => 'All Time', 'bn_name' => 'অল টাইম'],
            ['en_name' => 'Jhatpot', 'bn_name' => 'ঝটপট'],
            ['en_name' => 'Bisk Club', 'bn_name' => 'বিস্ক ক্লাব'],
            ['en_name' => 'Ahmed', 'bn_name' => 'আহমেদ'],
            ['en_name' => 'Meril', 'bn_name' => 'মেরিল'],
            ['en_name' => 'Unilever', 'bn_name' => 'ইউনিলিভার'],
            ['en_name' => 'Horlicks', 'bn_name' => 'হরলিক্স'],
            ['en_name' => 'GlaxoS D', 'bn_name' => 'গ্ল্যাক্সোস ডি'],
            ['en_name' => 'Boost', 'bn_name' => 'বুস্ট'],
            ['en_name' => 'Rin', 'bn_name' => 'রিন'],
            ['en_name' => 'Nestlé', 'bn_name' => 'নেসলে'],
            ['en_name' => 'Kitkat', 'bn_name' => 'কিটকাট'],
            ['en_name' => 'Maggi', 'bn_name' => 'ম্যাগি'],
            ['en_name' => 'Nescafe', 'bn_name' => 'নেসক্যাফে'],
            ['en_name' => 'Nido', 'bn_name' => 'নিডো'],
            ['en_name' => 'Coffee Mate', 'bn_name' => 'কফি মেট'],
            ['en_name' => 'Arla', 'bn_name' => 'আর্লা'],
            ['en_name' => 'DANO', 'bn_name' => 'ডানো'],
            ['en_name' => 'Cadbury', 'bn_name' => 'ক্যাডবেরি'],
            ['en_name' => 'Tang', 'bn_name' => 'ট্যাং'],
            ['en_name' => 'Oreo', 'bn_name' => 'ওরিও'],
            ['en_name' => "Foster Clark's", 'bn_name' => 'ফস্টার ক্লার্কস'],
            ['en_name' => 'Hajmola', 'bn_name' => 'হাজমোলা'],
            ['en_name' => 'Radhuni', 'bn_name' => 'রাঁধুনি'],
            ['en_name' => 'Ruchi', 'bn_name' => 'রুচি'],
            ['en_name' => 'Sun', 'bn_name' => 'সান'],
            ['en_name' => 'King', 'bn_name' => 'কিং'],
            ['en_name' => 'Pusti', 'bn_name' => 'পুষ্টি'],
            ['en_name' => 'Rupchanda', 'bn_name' => 'রূপচাঁদা'],
            ['en_name' => 'Marks', 'bn_name' => 'মার্কস'],
            ['en_name' => 'ACI Salt', 'bn_name' => 'এসিআই লবণ'],
            ['en_name' => 'Molla Salt', 'bn_name' => 'মোল্লা লবণ'],
            ['en_name' => 'Confidence Salt', 'bn_name' => 'কনফিডেন্স লবণ'],
            ['en_name' => 'Ispahani', 'bn_name' => 'ইস্পাহানি'],
            ['en_name' => 'Mum', 'bn_name' => 'মাম'],
            ['en_name' => 'Kinley', 'bn_name' => 'কিনলে'],
            ['en_name' => 'Aquafina', 'bn_name' => 'একুয়াফিনা'],
            ['en_name' => 'Spa', 'bn_name' => 'স্পা'],
            ['en_name' => 'Pran Up', 'bn_name' => 'প্রাণ আপ'],
            ['en_name' => 'Mojo', 'bn_name' => 'মোজো'],
            ['en_name' => 'Lemu', 'bn_name' => 'লেমু'],
            ['en_name' => 'RC Cola', 'bn_name' => 'আরসি কোলা'],
            ['en_name' => 'Coca-Cola', 'bn_name' => 'কোকাকোলা'],
            ['en_name' => 'Pepsi', 'bn_name' => 'পেপসি'],
            ['en_name' => '7 Up', 'bn_name' => 'সেভেন আপ'],
            ['en_name' => 'Sprite', 'bn_name' => 'স্প্রাইট'],
            ['en_name' => 'Fanta', 'bn_name' => 'ফান্টা'],
            ['en_name' => 'Mirinda', 'bn_name' => 'মিরিন্ডা'],
            ['en_name' => 'Mountain Dew', 'bn_name' => 'মাউন্টেন ডিউ'],
            ['en_name' => 'Slice', 'bn_name' => 'স্লাইস'],
            ['en_name' => 'Frooto', 'bn_name' => 'ফ্রুটো'],
            ['en_name' => 'Shezan', 'bn_name' => 'শেজান'],
            ['en_name' => 'Pran Frooto', 'bn_name' => 'প্রাণ ফ্রুটো'],
            ['en_name' => 'Frutika', 'bn_name' => 'ফ্রুটিকা'],
            ['en_name' => 'Uro', 'bn_name' => 'ইউরো'],
            ['en_name' => 'Danish', 'bn_name' => 'ড্যানিশ'],
            ['en_name' => 'Olympic', 'bn_name' => 'অলিম্পিক'],
            ['en_name' => 'Haque', 'bn_name' => 'হক'],
            ['en_name' => 'Nabisco', 'bn_name' => 'নাবিস্কো'],
            ['en_name' => 'Ifad Biscuit', 'bn_name' => 'ইফাদ বিস্কুট'],
            ['en_name' => 'Dekko', 'bn_name' => 'ডেকো'],
            ['en_name' => 'Fu-Wang Foods', 'bn_name' => 'ফু-ওয়াং ফুডস'],
            ['en_name' => 'Bombay Sweets', 'bn_name' => 'বোম্বে সুইটস'],
            ['en_name' => 'Pran Dairy', 'bn_name' => 'প্রাণ ডেইরি'],
            ['en_name' => 'Aarong Dairy', 'bn_name' => 'আড়ং ডেইরি'],
            ['en_name' => 'Milk Vita', 'bn_name' => 'মিল্ক ভিটা'],
            ['en_name' => 'Amul', 'bn_name' => 'আমুল'],
            ['en_name' => 'Igloo', 'bn_name' => 'ইগলু'],
            ['en_name' => 'Polar', 'bn_name' => 'পোলার'],
            ['en_name' => 'Bellisimo', 'bn_name' => 'বেলিসিমো'],
            ['en_name' => "Za 'n Zee", 'bn_name' => 'জা এন জি'],
            ['en_name' => 'Kazi Farms', 'bn_name' => 'কাজী ফার্মস'],
            ['en_name' => 'CP', 'bn_name' => 'সিপি'],
            ['en_name' => 'Golden Harvest', 'bn_name' => 'গোল্ডেন হারভেস্ট'],
            ['en_name' => 'Aftab', 'bn_name' => 'আফতাব'],
            ['en_name' => 'Pran Spice', 'bn_name' => 'প্রাণ মসলা'],
            ['en_name' => 'Radhuni Spice', 'bn_name' => 'রাঁধুনি মসলা'],
            ['en_name' => 'ACI Pure Spice', 'bn_name' => 'এসিআই পিওর মসলা'],
            ['en_name' => 'BD Spice', 'bn_name' => 'বিডি মসলা'],
            ['en_name' => 'Ahmed Spice', 'bn_name' => 'আহমেদ মসলা'],
            ['en_name' => 'Square Toiletries', 'bn_name' => 'স্কয়ার টয়লেট্রিজ'],
            ['en_name' => 'Keya', 'bn_name' => 'কেয়া'],
            ['en_name' => 'Lifebuoy', 'bn_name' => 'লাইফবয়'],
            ['en_name' => 'Lux', 'bn_name' => 'লাক্স'],
            ['en_name' => 'Dove', 'bn_name' => 'ডাভ'],
            ['en_name' => 'Sunsilk', 'bn_name' => 'সান্সিল্ক'],
            ['en_name' => 'Pantene', 'bn_name' => 'প্যানটিন'],
            ['en_name' => 'Head & Shoulders', 'bn_name' => 'হেড অ্যান্ড শোল্ডারস'],
            ['en_name' => 'Clear', 'bn_name' => 'ক্লিয়ার'],
            ['en_name' => 'Close up', 'bn_name' => 'ক্লোজ আপ'],
            ['en_name' => 'Pepsodent', 'bn_name' => 'পেপসোডেন্ট'],
            ['en_name' => 'Colgate', 'bn_name' => 'কোলগেট'],
            ['en_name' => 'Savlon', 'bn_name' => 'স্যাভলন'],
            ['en_name' => 'Dettol', 'bn_name' => 'ডেটল'],
            ['en_name' => 'Harpic', 'bn_name' => 'হারপিক'],
            ['en_name' => 'Domex', 'bn_name' => 'ডোমেক্স'],
            ['en_name' => 'Vim', 'bn_name' => 'ভিম'],
            ['en_name' => 'Wheel', 'bn_name' => 'হুইল'],
            ['en_name' => 'Surf Excel', 'bn_name' => 'সার্ফ এক্সেল'],
            ['en_name' => 'Tide', 'bn_name' => 'টাইড'],
            ['en_name' => 'Ariel', 'bn_name' => 'এরিয়েল'],
            ['en_name' => 'Parachute', 'bn_name' => 'প্যারাসুট'],
            ['en_name' => 'Kumarika', 'bn_name' => 'কুমারিকা'],
            ['en_name' => 'ACI Aerosol', 'bn_name' => 'এসিআই এরোসল'],
            ['en_name' => 'Good Knight', 'bn_name' => 'গুড নাইট'],
            ['en_name' => 'Xpel', 'bn_name' => 'এক্সপেল'],
            ['en_name' => 'Mortein', 'bn_name' => 'মর্টিন'],
            ['en_name' => 'Finis', 'bn_name' => 'ফিনিক্স'],
            ['en_name' => 'Godrej', 'bn_name' => 'গোদরেজ'],
            ['en_name' => 'ACI Cockroach Killer', 'bn_name' => 'এসিআই তেলাপোকা মারার স্প্রে'],
            ['en_name' => 'Hit', 'bn_name' => 'হিট'],
            ['en_name' => 'Lizol', 'bn_name' => 'লাইজল'],
            ['en_name' => 'Mr. Brasso', 'bn_name' => 'মিস্টার ব্রাসো'],
            ['en_name' => 'Dano Gold', 'bn_name' => 'ডানো গোল্ড'],
            ['en_name' => 'Diploma', 'bn_name' => 'ডিপ্লোমা'],
            ['en_name' => 'Farmland', 'bn_name' => 'ফার্মল্যান্ড'],
            ['en_name' => 'Anchor', 'bn_name' => 'অ্যাংকর'],
            ['en_name' => 'Cow & Gate', 'bn_name' => 'কাউ অ্যান্ড গেট'],
            ['en_name' => 'SMA', 'bn_name' => 'এসএমএ'],
            ['en_name' => 'NAN', 'bn_name' => 'ন্যান'],
            ['en_name' => 'Cerelac', 'bn_name' => 'সেরেল্যাক'],
            ['en_name' => 'Lactogen', 'bn_name' => 'ল্যাকটোজেন'],
            ['en_name' => 'Horlicks Junior', 'bn_name' => 'হরলিক্স জুনিয়র'],
            ['en_name' => 'Bournvita', 'bn_name' => 'বোর্নভিটা'],
            ['en_name' => 'Complan', 'bn_name' => 'কমপ্ল্যান'],
            ['en_name' => 'Maltova', 'bn_name' => 'মালটোভা'],
            ['en_name' => 'Ovaltine', 'bn_name' => 'ওভালটিন'],
            ['en_name' => 'Brooke Bond', 'bn_name' => 'ব্রুক বন্ড'],
            ['en_name' => 'Lipton', 'bn_name' => 'লিপটন'],
            ['en_name' => 'Taaza', 'bn_name' => 'তাজা'],
            ['en_name' => 'Tetley', 'bn_name' => 'টেটলি'],
            ['en_name' => 'HRC', 'bn_name' => 'এইচআরসি'],
            ['en_name' => 'Finlay', 'bn_name' => 'ফিনলে'],
            ['en_name' => 'Seylon', 'bn_name' => 'সিলন'],
            ['en_name' => 'Kissan', 'bn_name' => 'কিসসান'],
            ['en_name' => 'Heinz', 'bn_name' => 'হেইঞ্জ'],
            ['en_name' => 'Maggi Soup', 'bn_name' => 'ম্যাগি স্যুপ'],
            ['en_name' => 'Knorr', 'bn_name' => 'কনোর'],
            ['en_name' => 'Shan', 'bn_name' => 'শান'],
            ['en_name' => 'National', 'bn_name' => 'ন্যাশনাল'],
            ['en_name' => 'MDH', 'bn_name' => 'এমডিএইচ'],
            ['en_name' => 'Everest', 'bn_name' => 'এভারেস্ট'],
            ['en_name' => 'Pran Mustard Oil', 'bn_name' => 'প্রাণ সরিষার তেল'],
            ['en_name' => 'Radhuni Mustard Oil', 'bn_name' => 'রাঁধুনি সরিষার তেল'],
            ['en_name' => 'Teer Mustard Oil', 'bn_name' => 'তীর সরিষার তেল'],
            ['en_name' => 'Fresh Mustard Oil', 'bn_name' => 'ফ্রেশ সরিষার তেল'],
            ['en_name' => 'ACI Pure Mustard Oil', 'bn_name' => 'এসিআই পিওর সরিষার তেল'],
            ['en_name' => 'Rupchanda Mustard Oil', 'bn_name' => 'রূপচাঁদা সরিষার তেল'],
        ];

        foreach ($brands as $brand) {
            Brand::updateOrCreate(
                ['slug' => Str::slug($brand['en_name'])],
                [
                    'en_name' => $brand['en_name'],
                    'bn_name' => $brand['bn_name'],
                    'image' => 'images/brand/' . Str::slug($brand['en_name']) . '.jpg',
                ]
            );
        }

        // Enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}